import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:5001/#/adc-domain-saas/miniAppNotice');
  await page.getByRole('button', { name: '新 增' }).click();
  await page.getByRole('textbox', { name: '* APPID :' }).click();
  await page.getByRole('textbox', { name: '* APPID :' }).fill('208812123565');
  await page.getByRole('textbox', { name: '* 公告名称 :' }).click();
  await page.getByRole('textbox', { name: '* 公告名称 :' }).fill('test');
  await page.getByRole('textbox', { name: '* 公告点位 :' }).click();
  await page.getByRole('textbox', { name: '* 公告点位 :' }).fill('top');
  await page.getByLabel('公告描述').click();
  await page.getByLabel('公告描述').fill('desc');
  await page.getByLabel('公告内容').click();
  await page.getByLabel('公告内容').fill('notice');
  await page.getByRole('button', { name: '确 定' }).click();
  await page.getByRole('button', { name: 'Close' }).click();
  await page.getByRole('button', { name: '搜 索' }).click();
  await page.getByRole('button', { name: '清 除' }).click();
  await page.getByLabel('公告名称').click();
  await page.getByLabel('公告名称').fill('test');
  await page.getByRole('button', { name: '搜 索' }).click();
  await page.getByRole('button', { name: '清 除' }).click();
  await page.getByLabel('公告点位').fill('to');
  await page.getByLabel('公告点位').click();
  await page.getByLabel('公告点位').fill('top');
  await page.getByText('搜 索清 除').click();
  await page.getByRole('button', { name: '搜 索' }).click();
  await page.getByRole('button', { name: '清 除' }).click();
  await page.getByLabel('APPID').click();
  await page.getByLabel('APPID').fill('2088');
  await page.getByRole('button', { name: '搜 索' }).click();
  await page.getByRole('button', { name: '清 除' }).click();
  await page.locator('.ant-notification > div > div:nth-child(2)').click();
  await page.getByText('全部').click();
  await page.getByText('小黄条').click();
  await page.getByRole('button', { name: '搜 索' }).click();
  await page.locator('#searchForm').getByText('小黄条').click();
  await page.getByText('图片弹窗').click();
  await page.getByRole('button', { name: '搜 索' }).click();
  await page.locator('#searchForm').getByText('图片弹窗').click();
  await page.getByText('富文本弹窗').click();
  await page.getByRole('button', { name: '搜 索' }).click();
  await page.getByRole('button', { name: '清 除' }).click();
});